# Generated by Django 4.2 on 2026-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='商品名称')),
                ('price', models.FloatField(default=0, verbose_name='商品价格')),
                ('sezes', models.CharField(default='', max_length=100, verbose_name='颜色规格')),
                ('types', models.CharField(default='', max_length=100, verbose_name='商品类型')),
                ('discount', models.FloatField(default=0, verbose_name='折后价格')),
                ('stock', models.IntegerField(default=0, verbose_name='存货数量')),
                ('sold', models.IntegerField(default=0, verbose_name='已售数量')),
                ('likes', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('img', models.FileField(blank=True, null=True, upload_to='imgs', verbose_name='商品主图')),
                ('details', models.FileField(blank=True, null=True, upload_to='details', verbose_name='商品介绍')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('firsts', models.CharField(max_length=100, verbose_name='一级类型')),
                ('seconds', models.CharField(max_length=100, verbose_name='二级类型')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
    ]
